import 'package:freezed_annotation/freezed_annotation.dart';

part 'delete_admin_state.freezed.dart'; // This file will be generated by build_runner

@freezed
class DeleteAdminState<T> with _$DeleteAdminState<T> {
  const factory DeleteAdminState.initial() = _Initial; // Initial state

  const factory DeleteAdminState.loading() =
      Loading; // State when deletion is in progress
  const factory DeleteAdminState.success(T data) =
      Success<T>; // State on successful deletion
  const factory DeleteAdminState.error({required String error}) =
      Error; // State on deletion failure
}
